BTW TESTCASE FOR TYPECASTING
HAI
	SUM OF "17" AN "17"					BTW 34
	VISIBLE IT
	SUM OF 17 AN "17"					BTW 34
	VISIBLE IT
	BOTH SAEM "WIN" AN "WIN"				BTW WIN
	VISIBLE IT
	BOTH SAEM "WIN" AN FAIL					BTW FAIL
	VISIBLE IT
	BOTH OF WIN AN "WIN"					BTW WIN
	VISIBLE IT
	BOTH OF NOT FAIL AN NOT "FAIL"			BTW WIN
	VISIBLE IT
KTHXBYE