BTW SYNTAX CHECKER FOR ARITHMETIC
HAI
  BTW MISSING OPERAND
  DIFF OF

  BTW INVALID SYNTAX
  SUM OF 7 AN "7" DIFF OF 7 AN "7"

  BTW 2 CONSECUTIVE AN
  SUM OF 23 AN AN 24

  BTW 2 CONSECUTIVE OPERANDS
  SUM OF 23 24 AN 24

  BTW string on arithop
  SUM OF "var1" AN 6
  VISIBLE
KTHXBYE
