BTW boolean syntax checker
HAI
	I HAS A x ITZ WIN 
	I HAS A y ITZ FAIL
	I HAS A z ITZ FAIL

	BOTH OF x AN
	VISIBLE IT
	ALL OF NOT x AN BOTH OF y AN z AN EITHER OF x AN y MKAY
	VISIBLE IT
	ALL OF ALL OF x AN y MKAY AN z MKAY 
	VISIBLE IT
	BOTH OF a AN b
	VISIBLE IT
KTHXBYE