BTW for if-else statements
HAI
	BOTH SAEM 1 AN 1
	O RLY?
		YA RLY			
			VISIBLE "WIN"
		MEBBE BOTH SAEM 1 AN 2
			VISIBLE "1 AN 2 SAME"
		MEBBE BOTH SAEM 2 AN 2
			VISIBLE "2 AN 2 SAME"
		MEBBE BOTH SAEM 1 AN 1
			VISIBLE "1 AN 1 SAME"
		NO WAI
			VISIBLE "FAIL"
	VISIBLE "ALWAYS PRINTS"
KTHXBYE